# Generated by Django 3.1.12 on 2025-06-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_password', models.CharField(max_length=32)),
                ('e_gender', models.CharField(max_length=25)),
                ('e_contact', models.CharField(max_length=100)),
                ('e_address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=100)),
                ('o_email', models.EmailField(max_length=254)),
                ('o_password', models.CharField(max_length=32)),
                ('o_contact', models.CharField(max_length=100)),
                ('o_website', models.CharField(max_length=100)),
                ('o_address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.CharField(max_length=200)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='WorkProductivityDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_pds', models.CharField(max_length=255)),
                ('w_type', models.CharField(max_length=255)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'WorkProductivityDataset',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=55)),
                ('t_desc', models.CharField(max_length=200)),
                ('t_status', models.CharField(max_length=55)),
                ('t_priority', models.CharField(max_length=30)),
                ('t_assign_date', models.CharField(max_length=55)),
                ('t_deadline_date', models.CharField(max_length=55)),
                ('t_update_date', models.CharField(max_length=55, null=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardids', to='app.board')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeids', to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectids', to='app.project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='ScreenShotsMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssm_img', models.CharField(max_length=255)),
                ('ssm_log_ts', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'ScreenShotsMonitoring',
            },
        ),
        migrations.CreateModel(
            name='PowerMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_status', models.CharField(max_length=255)),
                ('pm_log_ts', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'PowerMonitoring',
            },
        ),
        migrations.CreateModel(
            name='OrganizationNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_title', models.CharField(max_length=255)),
                ('on_desc', models.TextField(max_length=255)),
                ('on_date_time', models.DateTimeField(auto_now=True)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'OrganizationNews',
            },
        ),
        migrations.CreateModel(
            name='MonitoringDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_title', models.CharField(max_length=200)),
                ('md_total_time_seconds', models.CharField(max_length=200)),
                ('md_date', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'MonitoringDetails',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(max_length=200, null=True)),
                ('m_log_ts', models.CharField(max_length=200)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'monitoring',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=55)),
                ('m_desc', models.CharField(max_length=200)),
                ('m_uuid', models.CharField(max_length=200)),
                ('m_start_date', models.CharField(max_length=55)),
                ('m_stop_date', models.CharField(max_length=55)),
                ('m_start_time', models.CharField(max_length=55)),
                ('m_stop_time', models.CharField(max_length=55)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_reason', models.CharField(max_length=55)),
                ('l_desc', models.CharField(max_length=200)),
                ('l_start_date', models.CharField(max_length=55)),
                ('l_no_of_leaves', models.PositiveIntegerField()),
                ('l_status', models.CharField(max_length=55)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'leaves',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='o_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.AddField(
            model_name='board',
            name='o_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.CharField(max_length=55)),
                ('a_time', models.CharField(max_length=55)),
                ('a_status', models.CharField(max_length=55)),
                ('a_ip_address', models.CharField(max_length=55)),
                ('a_time_zone', models.CharField(max_length=55)),
                ('a_lat', models.CharField(max_length=55)),
                ('a_long', models.CharField(max_length=55)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
            options={
                'db_table': 'AttendanceLogs',
            },
        ),
        migrations.CreateModel(
            name='Project_Employee_Linker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'db_table': 'project_emp_assign',
                'unique_together': {('p_id', 'e_id', 'o_id')},
            },
        ),
    ]
