# Generated by Django 3.1.12 on 2025-07-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="A unique code for the permission (e.g., 'view_logs')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='A human-readable name for the permission', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the permission', null=True)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the role (e.g., 'Manager', 'Developer')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the role', null=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='roles', to='app.Permission')),
            ],
            options={
                'db_table': 'role',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The role assigned to this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.role'),
        ),
    ]
