# Generated by Django 3.1.12 on 2025-08-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250723_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotsmonitoring',
            name='ssm_img',
            field=models.TextField(max_length=255),
        ),
    ]
